variables:
  KUBE_NAMESPACE: "fgils-1"
  IMAGE_NAME: "lisa"
  APP_VERSION: "v0.0.1"
  DEPLOY_REGEX: /^v\d+\.\d+\.\d+$/
  IMAGE_REPOSITORY: "ghcr.io/noahlehmann/talk-daily-automations"

stages:
  - lint
  - test
  - build
  - deploy

.deploy_rules:
  rules:
    - if: $CI_COMMIT_TAG =~ $DEPLOY_REGEX
      when: always
    - when: never

test_api:
  stage: test
  tags:
    - docker
  image: python:3.13-alpine
  script:
    - pip install -r src/api/requirements.txt
    - pytest src/api/test_app.py --disable-warnings

lint_api:
  stage: lint
  tags:
    - docker
  image: python:3.13-alpine
  script:
    - pip install ruff
    - ruff check src/api

lint_web:
  stage: lint
  tags:
    - docker
  image: node:20-alpine
  script:
    - npm install -g eslint
    - npx eslint src/web/main.js src/web/config.*js --stats --exit-on-fatal-error

build_helm:
  stage: build
  dependencies:
    - lint_api
    - lint_web
    - test_api
  tags:
    - docker
  image: alpine/k8s:1.31.7
  script:
    - echo "Packaging version ${APP_VERSION} and app version ${APP_VERSION}"
    - helm package ./chart/counter --dependency-update --version "${APP_VERSION}" --app-version "${APP_VERSION}" --destination .
  artifacts:
    paths:
      - "counter-${APP_VERSION}.tgz"

deploy_helm:
  extends: .deploy_rules
  dependencies:
    - build_helm
  stage: deploy
  tags:
    - docker
  image: alpine/k8s:1.31.7
  script:
    - IMAGE_TAG="${CI_COMMIT_TAG:-$APP_VERSION}"
    - echo "Upgrading counter-example to version ${APP_VERSION} with image tag ${IMAGE_TAG}"
    - echo "Using chart counter-${APP_VERSION}.tgz"
    - >
      helm upgrade --install
      counter-example ./counter-${APP_VERSION}.tgz
      --kubeconfig $KUBECONFIG 
      --namespace $KUBE_NAMESPACE
      --set api.image.repository="${IMAGE_REPOSITORY}/api"
      --set web.image.repository="${IMAGE_REPOSITORY}/web"
      --set api.image.tag="${IMAGE_TAG}"
      --set web.image.tag="${IMAGE_TAG}"
      --set postgres.auth.password="${POSTGRES_USER_PASSWORD}"
