services:
  api:
    build:
      context: ./src/api
      dockerfile: Containerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/db
    expose:
      - "8080"
    depends_on:
      - postgres

  web:
    build:
      context: ./src/web
      dockerfile: Containerfile
      args:
        ENV: compose
    ports:
      - "80:80"
    volumes:
      - ./src/web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

volumes:
  pg_data: {}
