services:
  api:
    build:
      context: ./src/api
      dockerfile: ./build/api/Containerfile
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/db

  web:
    build:
      context: ./src/web
      dockerfile: ./build/web/Containerfile
    environment:
      API_URL: http://api:3000

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db