---
- name: Setup LXC container
  hosts: "prometheus_local"
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Ensure locale exists
      community.general.locale_gen:
        name: "{{ prometheus.locale }}"
        state: present

    - name: Ensure language locale exists
      community.general.locale_gen:
        name: "{{ prometheus.language }}"
        state: present

    - name: Get current locale configuration
      ansible.builtin.command: "localectl status"
      register: locale_status
      changed_when: false
      failed_when: false

    - name: Parse 'LANG' from current locale and language configuration
      set_fact:
        locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | default(['none'], true) | first }}"

    - name: Parse 'LANGUAGE' from current locale and language configuration
      set_fact:
        locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

    - name: Configure locale to '{{ prometheus.locale }}' and language to '{{ prometheus.language }}'
      become: yes
      command: localectl set-locale LANG={{ prometheus.language }} LANGUAGE={{ prometheus.locale }}
      changed_when: ( locale_lang != prometheus.language ) or ( locale_language != prometheus.locale )

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - unzip
        state: present
