FROM library/python:3.11-slim-bookworm

ARG USER=dev
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install -y --no-install-recommends sudo git make \
    && apt autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -m -s /usr/bin/bash ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/${USER} \
    && chmod 0440 /etc/sudoers.d/${USER}

RUN pip install --upgrade pip

RUN pip install --no-cache-dir ggshield # pre-commit hook
RUN ggshield install -m global

#RUN make init
