FROM python:3.13-alpine

WORKDIR /app

COPY . .

RUN apk add --no-cache curl

RUN pip install --upgrade pip && \
    pip install -r requirements.txt


ENV FLASK_APP=app.py
CMD flask db upgrade && flask run --host=0.0.0.0 --port=8080