apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "counter.fullname" . }}-api
  labels:
    {{- include "counter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "counter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "counter.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "counter.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DATABASE_URL
              value: {{ include "counter.databaseURL" . | quote }}
